app:
    resource: "@JukeboxBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

video:
    path:      /video
    defaults:  { _controller: JukeboxBundle:Video:index }

video/new:
    path:      /video/new
    defaults:  { _controller: JukeboxBundle:Video:new }

video/detail:
    path:       /video/{video_id}
    defaults:  { _controller: JukeboxBundle:Video:detail }

video/delete:
    path:       /video/{video_id}/delete
    defaults:   { _controller: JukeboxBundle:Video:delete }

video/edit:
    path:       /video/{video_id}/edit
    defaults:   { _controller: JukeboxBundle:Video:edit }

play:
    path:       /play
    defaults:   { _controller: JukeboxBundle:Video:play }

manage_users:
    path:       /manage_users
    defaults:   { _controller: JukeboxBundle:User:index }

manage_users/detail:
    path:       /manage_users/{user_id}/detail
    defaults:   { _controller: JukeboxBundle:User:detail }