app:
    resource: "@JukeboxBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

video:
    path:      /video
    defaults:  { _controller: JukeboxBundle:Video:index }

video/new:
    path:      /video/new
    defaults:  { _controller: JukeboxBundle:Video:new }

video/detail:
    path:       /video/detail/{video_id}
    defaults:  { _controller: JukeboxBundle:Video:detail }
