app:
    resource: "@JukeboxBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

video:
    path:      /video
    defaults:  { _controller: JukeboxBundle:Video:index }



